const countiesCities = {
    "Aberdeen": ["Aberdeen", "Ellon", "Fraserburgh", "Inverurie", "Peterhead", "Turriff"],
    "Angus": ["Forfar", "City of Dundee", "Arbroath", "Brechin", "Carnoustie", "Kirriemuir", "Montrose"],
    "Caernarfonshire": ["Bangor", "Caernarfon", "Llandudno", "Conwy", "Pwllheli", "Porthmadog"],
    "County Armagh": ["City of Armagh", "City of Newry", "Craigavon", "Bessbrook", "Crossmaglen", "Keady", "Laurelvale", "Markethill", "Mullavilly", "Poyntzpass", "Richhill", "Tandragee"],
    "County Down": ["Ballynahinch", "Bangor", "Banbridge", "Carryduff", "Comber", "Donaghadee", "Downpatrick", "Dromore", "Dundonald", "Holywood", "Kilkeel", "Newcastle", "Newtownards", "Warrenpoint"],
    "County Durham": ["Auckland St Andrew", "Auckland St Helen", "Aycliffe", "Barnard Castle", "Billingham", "Bishop Auckland", "Bishop Middleham", "Bishopton", "Bishopwearmouth", "Boldon", "Brancepeth", "Burnmoor", "Chester-le-Street", "Cockfield", "Coniscliffe", "Croxdale", "Dalton-le-Dale", "Darlington", "Denton", "Dinsdale", "Durham", "Easington", "Ebchester", "Edmundbyers", "Egglescliffe", "Egglestone", "Elton", "Elwick Hall", "Embleton", "Escomb", "Esh", "Gainford", "Gateshead", "Greatham", "Hamsterley", "Hart", "Hartlepool", "Heathery Cleugh", "Heworth", "Houghton-le-Spring", "Hunstanworth", "Hurworth", "Jarrow", "Jarrow St Mark", "Jarrow St Mary", "Jarrow St Paul", "Jarrow St Peter", "Jarrow Grange Christ Church", "Jarrow Grange Good Shepherd", "Kelloe", "Lanchester", "Long Newton", "Medomsley", "Merrington", "Middleton-in-Teesdale", "Middleton St George", "Monk Hesledon", "Monkwearmouth", "Muggleswick", "Norton", "Penshaw", "Pittington", "Redmarshall", "Rookhope", "Ryton", "Sadberge", "Seaham", "Sedgefield", "South Shields", "Staindrop", "Stanhope", "Stillington", "Stockton-on-Tees", "Stranton", "Sunderland", "Tanfield", "Trimdon", "Washington", "West Rainton", "Whickham", "Whitburn", "Witton-le-Wear", "Wolsingham"],
    "County Down": ["Ballynahinch", "Bangor", "Banbridge", "Carryduff", "Comber", "Donaghadee", "Downpatrick", "Dromore", "Dundonald", "Holywood", "Kilkeel", "Newcastle", "Newtownards", "Warrenpoint"],
    "County Fermanagh": ["Enniskillen", "Irvinestown", "Lisnaskea", "Maguiresbridge", "Newtownbutler", "Roslea", "Slate", "Ballinamallard"],
    "County Kildare": ["Athy", "Clane", "Newbridge", "Naas", "Celbridge", "Leixlip", "Kilcullen", "Rathangan"],
    "County Kilkenny": ["Kilkenny", "Thomastown", "Ballyragget", "Castlecomer", "Graiguenamanagh", "Callan", "Freshford"],
    "County Limerick": ["Limerick", "Kilmallock", "Croom", "Adare", "Newcastle West", "Ballyneety"],
    "County Louth": ["Dundalk", "Drogheda", "Ardee", "Dunleer", "Carlingford", "Cullen"],
    "County Meath": ["Navan", "Trim", "Ashbourne", "Kells", "Dunshaughlin", "Summerhill"],
    "County Monaghan": ["Monaghan", "Carrickmacross", "Castleblayney", "Clones", "Scotstown", "Ballybay"],
    "County Offaly": ["Tullamore", "Birr", "Edenderry", "Clara", "Banagher"],
    "County Roscommon": ["Roscommon", "Athlone", "Boyle", "Castlerea", "Ballaghaderreen", "Tarmonbarry", "Strokestown"],
    "County Sligo": ["Sligo", "Enniscrone", "Ballymote", "Tubbercurry", "Collooney", "Grange", "Easkey"],
    "County Tipperary": ["Clonmel", "Nenagh", "Thurles", "Cahir", "Carrick-on-Suir", "Templemore"],
    "County Waterford": ["Waterford", "Dungarvan", "Tramore", "Lismore", "Tallow", "Clonea", "Kilmacthomas"],
    "County Wexford": ["Wexford", "Gorey", "Enniscorthy", "New Ross", "Ferns", "Bunclody"],
    "Cumbria": ["Carlisle", "Workington", "Cockermouth", "Harrington", "Keswick", "Maryport", "Silloth", "Whitehaven", "Egremont", "Millom", "Penrith", "Alston", "Aspatria", "Brampton", "Cleator Moor", "Dalston", "Longtown", "Wigton"],
    "Dorset": ["Dorchester", "Bournemouth", "Poole", "Weymouth", "Christchurch", "Sherborne", "Bridport", "Sturminster Newton", "Wareham"],
    "Durham": ["Darlington", "Bishop Auckland", "Chester-le-Street", "Hartlepool", "Middlesbrough", "Newcastle", "Stockton-on-Tees", "Sunderland"],
    "East Sussex": ["Brighton", "Hastings", "Lewes", "Eastbourne", "Bexhill", "Battle", "Seaford", "Uckfield", "Crowborough"],
    "Essex": ["Chelmsford", "Southend-on-Sea", "Barking", "Basildon", "Benfleet", "Billericay", "Braintree", "Brentwood", "Brightlingsea", "Burnham-on-Crouch", "Canning Town", "Canvey Island", "Chingford", "Chigwell", "Chipping Ongar", "Clacton-on-Sea", "Coggeshall", "Colchester", "Dovercourt", "East Ham", "Epping", "Frinton-on-Sea", "Grays", "Great Dunmow", "Hadleigh", "Halstead", "Harlow", "Harwich", "Holland-on-Sea", "Hornchurch", "Ilford", "Leyton", "Leytonstone", "Loughton", "Maldon", "Manningtree", "Rainham", "Rochford", "Romford", "Saffron Walden", "Shoeburyness", "Silvertown", "South Ockendon", "South Woodham Ferrers", "Stanford-le-Hope", "Stratford", "Tilbury", "Upminster", "Waltham Abbey", "Walthamstow", "Walton-on-the-Naze", "West Ham", "Wickford", "Witham", "Wivenhoe", "Woodford"],
    "Gloucestershire": ["Gloucester", "Cheltenham", "Cirencester", "Stroud", "Tewkesbury", "Cheltenham", "Dursley", "Kingswood", "Lechlade", "Minchinhampton", "Moreton-in-Marsh", "Nailsworth", "Patchway", "Stow-on-the-Wold", "Tetbury", "Thornbury", "Wotton-under-Edge", "Yate"],
    "Greater London": ["London", "Croydon", "Barnet", "Brent", "Hackney", "Haringey", "Islington", "Lambeth", "Lewisham", "Merton", "Newham", "Redbridge", "Richmond", "Southwark", "Sutton", "Tower Hamlets", "Waltham Forest"],
    "Greater Manchester": ["Manchester", "Bolton", "Bury", "Oldham", "Rochdale", "Salford", "Stockport", "Tameside", "Trafford", "Wigan"],
    "Hampshire": ["Southampton", "Portsmouth", "Basingstoke", "Farnborough", "Fleet", "Havant", "Andover", "Alton", "Bordon", "Romsey", "Lymington", "Liss", "Petersfield", "Winchester"],
    "Hertfordshire": ["Watford", "Hemel Hempstead", "Stevenage", "Hitchin", "Welwyn Garden City", "St Albans", "Hatfield", "Berkhamsted", "Chesham", "Chorleywood", "Kings Langley", "Rickmansworth", "Buntingford", "Tring"],
    "Humberside": ["Kingston-upon-Hull", "Grimsby", "Scunthorpe", "Cleethorpes", "Brigg", "Barton-upon-Humber"],
    "Kent": ["Canterbury", "Rochester", "Ashford", "Bexleyheath", "Biggin Hill", "Broadstairs", "Bromley", "Catford", "Chatham", "Cranbrook", "Dartford", "Deptford", "Deal", "Dover", "Edenbridge", "Eltham", "Faversham", "Folkestone", "Gillingham", "Greenwich", "Herne Bay", "Hythe", "Kingsdown", "Lydd", "Maidstone", "Margate", "New Romney", "Northfleet", "Orpington", "Paddock Wood", "Ramsgate", "Ringwould", "Royal Tunbridge Wells", "Sandwich", "Sheerness", "Sittingbourne", "Snodland", "Strood", "Swanley", "Tenterden", "Tonbridge", "Walmer", "West Malling", "Westerham", "Whitstable", "Woolwich"],
    "Lancashire": ["Lancaster", "Liverpool", "Manchester", "Preston", "Salford", "Accrington", "Ashton-under-Lyne", "Barrow-in-Furness", "Blackburn", "Blackpool", "Bootle", "Bolton", "Burnley", "Bury", "Chorley", "Clitheroe", "Colne", "Fleetwood", "Formby", "Leigh", "Leyland", "Lytham St Annes", "Nelson", "Morecambe", "Oldham", "Ormskirk", "Rochdale", "Skelmersdale", "Southport", "St Helens", "Thornton-Cleveleys", "Warrington", "Widnes", "Wigan"],
    "Leicestershire": ["Leicester", "Loughborough", "Hinckley", "Coalville", "Melton Mowbray", "Market Harborough", "Oadby", "Ashby-de-la-Zouch", "Ibstock", "Syston"],
    "Lincolnshire": ["Lincoln", "Grimsby", "Cleethorpes", "Boston", "Skegness", "Spalding", "Louth", "Horncastle", "Stamford", "Sleaford", "Gainsborough"],
    "Merseyside": ["Liverpool", "Wirral", "St Helens", "Southport", "Bootle", "Wallasey"],
    "Norfolk": ["Norwich", "Great Yarmouth", "King's Lynn", "Thetford", "Dereham", "Cromer", "Holt", "North Walsham", "Attleborough", "Fakenham"],
    "Northumberland": ["Newcastle upon Tyne", "Hexham", "Alnwick", "Ashington", "Cramlington", "Morpeth", "North Shields", "South Shields", "Tynemouth", "Berwick-upon-Tweed"],
    "North Yorkshire": ["York", "Harrogate", "Scarborough", "Ripon", "Leeds", "Sheffield", "Middlesbrough", "Richmond", "Thirsk", "Whitby", "Knaresborough"],
    "Nottinghamshire": ["Nottingham", "Mansfield", "Ashfield", "Worksop", "Newark", "Ilkeston", "Arnold", "Rushcliffe", "Bingham", "Eastwood"],
    "Oxfordshire": ["Oxford", "Abingdon", "Banbury", "Bicester", "Didcot", "Witney", "Wallingford", "Kidlington"],
    "Shropshire": ["Shrewsbury", "Telford", "Ludlow", "Oswestry", "Bridgnorth", "Market Drayton"],
    "Somerset": ["Axminster", "Bampton", "Black Torrington", "Braunton", "Colyton", "Crediton", "Exminster", "Fremington", "Halberton", "Hartland", "Haytor", "Hemyock", "Lifton", "North Tawton", "Ottery St Mary", "Plympton", "Roborough", "Shebbear", "Shirwell", "South Molton", "Stanborough", "Tavistock", "Teignbridge", "Tiverton", "West Budleigh", "Witheridge", "Wonford"],
    "South Yorkshire": ["Sheffield", "Barnsley", "Doncaster", "Rotherham", "Wakefield"],
    "Staffordshire": ["Stoke-on-Trent", "Stafford", "Lichfield", "Tamworth", "Newcastle-under-Lyme", "Cannock", "Burton-upon-Trent", "Rugeley", "Wolverhampton"],
    "Suffolk": ["Ipswich", "Bury St Edmunds", "Lowestoft", "Stowmarket", "Felixstowe", "Newmarket", "Sudbury", "Mildenhall", "Haverhill"],
    "Surrey": ["Guildford", "Woking", "Farnham", "Epsom", "Reigate", "Camberley", "Cranleigh", "Godalming"],
    "Tyne and Wear": ["Newcastle", "Gateshead", "Sunderland", "North Shields", "South Shields", "Tynemouth"],
    "Warwickshire": ["Warwick", "Coventry", "Nuneaton", "Rugby", "Leamington Spa", "Stratford-upon-Avon", "Kenilworth", "Bedworth"],
    "West Midlands": ["Birmingham", "Coventry", "Wolverhampton", "Walsall", "Dudley", "Solihull"],
    "West Sussex": ["Chichester", "Worthing", "Horsham", "Bognor Regis", "Crawley", "East Grinstead", "Haywards Heath", "Lancing", "Petworth", "Steyning", "Uckfield"],
    "West Yorkshire": ["Leeds", "Bradford", "Wakefield", "Huddersfield", "Halifax", "Castleford", "Dewsbury", "Harrogate", "Keighley"],
    "Wiltshire": ["Swindon", "Salisbury", "Chippenham", "Trowbridge", "Marlborough", "Warminster", "Devizes"],
    "Worcestershire": ["Worcester", "Redditch", "Evesham", "Malvern", "Bromsgrove", "Droitwich", "Kidderminster"],
    "Yorkshire and the Humber": ["Leeds", "York", "Sheffield", "Bradford", "Hull", "Wakefield"]
};

module.exports = countiesCities;
